# Generated by Django 2.2.5 on 2020-02-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='table_id',
            field=models.IntegerField(null=True),
        ),
    ]
