# Generated by Django 3.0.4 on 2020-10-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0002_project_table_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge_assignment',
            name='ja_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
