# Generated by Django 2.2 on 2020-10-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0003_auto_20201015_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='no_show',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='no_show',
            field=models.BooleanField(default=False),
        ),
    ]
